server:
  port: 8080
  servlet:
    context-path: "/hotel"
#  ssl:
#    key-store: classpath:mafangui.cn.jks
#    key-store-password: 98cy27738t8
#    key-store-type: JKS
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: muamua
    password: muamua
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
mybatis:
  type-aliases-package: classpath*:cn.mafangui.hotel.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml

